name: TopSH

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: make test_unit
      - name: E2E tests
        run: make test_e2e
